# Generated by Django 3.0 on 2021-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
