# Generated by Django 3.0 on 2021-07-25 06:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of User')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Customer's primary mobile number e.g. +91{10 digit mobile number}", max_length=128, region=None, unique=True, verbose_name='Mobile Number')),
            ],
        ),
        #migrations.RemoveField(
        #    model_name='usersessionhistory',
        #    name='user',
        #),
       # migrations.RemoveField(
        #    model_name='user',
        #    name='user_name',
        #),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
        #migrations.AlterField(
        #    model_name='user',
        #    name='phone_number',
        #    field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Customer's primary mobile number e.g. +91{10 digit mobile number}", max_length=128, region=None, unique=True, verbose_name='Mobile Number'),
        #),
        #migrations.DeleteModel(
        #    name='UserSession',
        #),
       # migrations.DeleteModel(
       #     name='UserSessionHistory',
       # ),
    ]
