# Generated by Django 3.0 on 2021-07-25 06:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210725_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Customer's primary mobile number e.g. +91{10 digit mobile number}", max_length=128, region=None, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserSessionHistory',
        ),
    ]
