# Generated by Django 3.0 on 2021-07-25 07:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Fb', 'Fb'), ('WebSite', 'WebSite'), ('Google', 'Google')], default='Fresh', max_length=60, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=django_fsm.FSMField(db_index=True, default='Fresh', max_length=50),
        ),
    ]
